# -*- coding: utf-8 -*-
"""kal-sentiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OCdWiVhh0368t3Lg-5rn8tMH251FI7HW
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install transformers datasets accelerate scikit-learn -q

import torch

print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

import pandas as pd
import numpy as np

from datasets import Dataset

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer
)

from sklearn.metrics import accuracy_score, f1_score

# =====================
# LOAD DATA
# =====================

train_path = "/content/drive/MyDrive/Colab/kal-sentiment/data/train.csv"
test_path = "/content/drive/MyDrive/Colab/kal-sentiment/data/test.csv"

train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)

# ambil kolom
train_df = train_df[["clean_comment", "label_id"]]
test_df = test_df[["clean_comment", "label_id"]]

# rename
train_df.columns = ["text", "label"]
test_df.columns = ["text", "label"]

# convert dataset
train_dataset = Dataset.from_pandas(train_df)
test_dataset = Dataset.from_pandas(test_df)

# =====================
# TOKENIZER
# =====================

model_name = "indobenchmark/indobert-base-p1"

tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize_function(data):

    return tokenizer(
        data["text"],
        padding="max_length",
        truncation=True,
        max_length=128
    )

train_dataset = train_dataset.map(tokenize_function)
test_dataset = test_dataset.map(tokenize_function)

# =====================
# MODEL
# =====================

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=3
)

# =====================
# METRIC
# =====================

def compute_metrics(eval_pred):

    logits, labels = eval_pred

    predictions = np.argmax(logits, axis=-1)

    acc = accuracy_score(labels, predictions)

    f1 = f1_score(
        labels,
        predictions,
        average="weighted"
    )

    return {
        "accuracy": acc,
        "f1": f1
    }

# =====================
# TRAINING ARGUMENT
# =====================

training_args = TrainingArguments(
    output_dir="./results",

    eval_strategy="epoch",
    save_strategy="epoch",

    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,

    num_train_epochs=3,

    logging_steps=10,

    load_best_model_at_end=True
)

# =====================
# TRAINER
# =====================

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics
)

# =====================
# TRAIN
# =====================

trainer.train()

# =====================
# EVALUASI
# =====================

result = trainer.evaluate()

print(result)

# =====================
# SAVE MODEL
# =====================

save_path = "/content/drive/MyDrive/Colab/kal-sentiment/sentiment_model_02"

trainer.save_model(save_path)

tokenizer.save_pretrained(save_path)

print("Model saved")